### ISSUE TITLE
con_logfile should have .log in the extension name

### ISSUE THREAD

**Issue by ghost** [axynos/STARK#12]
Hi,

``con_logfile`` should have ``.log`` in the extension name, otherwise CS:GO won't write to that file.

Cheers.

// waiting for the v2 :-)

**Comment by axynos** [comment]
Hey!

Thanks for reaching out on such an old project! Unfortunately since I've gone on to work on other things both in software and outside of software, it's highly unlikely that I'll ever complete v2 unless there is significant interest from the community.
I don't really play video games anymore, so the program itself does not give much value to me, which is why I haven't picked up the project again.

That said, if I do get back to working on this someday, I'll keep your note in mind. :)
