### ISSUE TITLE
Hey, can you fix this ?

### ISSUE THREAD

**Issue by muratcansimsek** [axynos/STARK#13]
Can you really fix this and make it work?

**Comment by axynos** [comment]
Hey!

I appreciate you taking the time to reach out. Unfortunately, I have made the decision to abandon the project as developing v2 and maintaining the project would take up a lot of my time. That would be fine if I was still an active participant in the gaming space, but I have since gone on to lead multiple non-tech teams in the nonprofit and edtech space.

In order to have time to myself and take care of my mental health, I have decided that I will not make the promise of ever developing v2 of this project and completely abandon v1. If (and this is a tiny chance) I do work on it again, it's going to be purely for my own entertainment and in case I do release anything, it will be given to the community to actively maintain.

I am incredibly grateful for the lasting interest in this project, I couldn't have predicted the impact it had on people. But as with all things, this too shall pass.

- Silver

**Comment by fuck-shithub** [comment]
If you want something that works, you can try my fork: https://github.com/GrimReaperFloof/STARK

Recently, I've also done an attempt at remaking STARK in Python: https://github.com/GrimReaperFloof/SourceDJ
It's probably still glitchy so I recommend my STARK fork over it, but so far, it does TTS (Google TTS, `.tts <text>`), and can play videos from YouTube (`.play <search query>`). It uses PyAudio (PortAudio) as audio backend, so it can work on Linux as well, unlike STARK.
